# Generated by Django 4.2 on 2025-11-17 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Adoptado', 'Adoptado'), ('En adopción', 'En adopción')], default='En adopción', max_length=15)),
                ('nombre_mascota', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateTimeField(verbose_name='Fecha de publicación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='nombre_mascota/%Y/%m/%d')),
                ('especie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mascotas.especie')),
            ],
        ),
    ]
