# Generated by Django 4.2 on 2025-11-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mascota',
            name='sexo',
            field=models.CharField(default='No especificado', max_length=20),
        ),
    ]
