# Generated by Django 4.2 on 2025-10-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto',
            new_name='nombre_producto',
        ),
    ]
