# Generated by Django 4.2 on 2025-10-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vistaprevia', '0003_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='nombre_producto/%Y/%m/%d'),
        ),
    ]
